/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bbcba36701c57c3014763d8b166f1456)
interface __BaseEnv_Env {
	MEDIA_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	DATABASE_URL: string;
	AUTH_SECRET: string;
	RESEND_API_KEY: string;
	EMAIL_FROM: string;
	APP_URL: string;
	OPENAI_API_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	STRIPE_SUBSCRIPTION_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "AUTH_SECRET" | "RESEND_API_KEY" | "EMAIL_FROM" | "APP_URL" | "OPENAI_API_KEY" | "STRIPE_SECRET_KEY" | "STRIPE_WEBHOOK_SECRET" | "STRIPE_SUBSCRIPTION_WEBHOOK_SECRET">> {}
}
